server:
  port: 8081

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      auto-offset-reset: earliest
      enable-auto-commit: false

  datasource:
    url: jdbc:postgresql://localhost:5434/paymentdb
    username: paymentuser
    password: paymentpass

    hikari:
      max-lifetime: 270000
      idle-timeout: 240000
      minimum-idle: 2
      maximum-pool-size: 10
      connection-timeout: 30000
      leak-detection-threshold: 20000

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

logging:
  level:
    root: INFO
    com.vikas: DEBUG
    org.springframework: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: OFF
    org.apache.kafka.clients.producer.ProducerConfig: OFF
